matrix:
  - name: "Markdown"
    sources:
      - "docs/*.md"
    aspell:
      lang: en
      d: en_US
    pipeline:
      - pyspelling.filters.markdown:
    dictionary:
      wordlists:
        - ".github/.wordlist.txt"
